trainer: gnn
output_dir: /gpfs/alpine/world-shared/stf011/atsaris/gnn_results_md_out/test

data:
    name: parse_md_gcn
    n_train: 60
    n_valid: 14
    ### input_dir: '/gpfs/alpine/stf011/world-shared/atsaris/datagnn/datagnn_ras_2020/graph_kRas_monomer_large'
    #filelist: '/ccs/proj/stf011/atsaris/august2020/gnn_new/gnn-protmd/filelist/test.KRAS_WT_r0.csv'
    #filelist: '/ccs/proj/stf011/atsaris/august2020/gnn-protmd/filelists/temporal/KRAS_WT_r0_small.csv'
    filelist: '/autofs/nccs-svm1_proj/stf011/atsaris/august2020/gnn_new/gnn-protmd/filelist/tmp.csv'
    batch_size: 32

model:
    name: mpnn6
    n_node_features: 24
    n_edge_features: 1
    hidden_size: 16
    n_outputs: 1
    loss_function: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    lr: 0.001

training:
    n_epochs: 100
