trainer: gnn
output_dir: /gpfs/alpine/world-shared/stf011/atsaris/gnn_results_out/mpnn_bzrmd

data:
    name: tud
    tud_name: BZR_MD
    n_train: 256
    n_valid: 128
    batch_size: 1 #8
    download_path: '/gpfs/alpine/world-shared/stf011/atsaris/gnn_benchmarks_data'

model:
    name: mpnn
    n_node_features: 8
    n_edge_features: 6
    hidden_size: 16
    n_outputs: 1
    loss_function: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    lr: 0.001

training:
    n_epochs: 128
