trainer: gnn
output_dir: /gpfs/alpine/world-shared/stf011/atsaris/gnn_results_md_out/mpnn_bzrmd_sDev

data:
    name: parse_md
    n_train: 8
    n_valid: 2
    ###input_dir: '/gpfs/alpine/world-shared/stf011/atsaris/datagnn/datagnn_ras_2020/graph_full_kRas'
    filelist: '/ccs/proj/stf011/atsaris/may2020/gnn-protmd/filelists/graph_full_kRas.csv'
    batch_size: 32

model:
    name: mpnn3
    n_node_features: 25
    n_edge_features: 1 #6
    hidden_size: 16
    n_outputs: 1
    loss_function: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    lr: 0.001

training:
    n_epochs: 100
