trainer: gnn
output_dir: /Users/28t/Downloads/tmp

data:
    name: parse_mdRNN
    n_train: 1
    n_valid: 1
    ### input_dir: '/gpfs/alpine/stf011/world-shared/atsaris/datagnn/datagnn_ras_2020/graph_kRas_monomer_large'
    filelist: 'filelist/tmp.csv'
    batch_size: 32

model:
    name: mpnn3RNN
    n_node_features: 24
    n_edge_features: 3
    hidden_size: 16
    n_outputs: 1
    loss_function: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    lr: 0.001

training:
    n_epochs: 1
