trainer: gnn
output_dir: /gpfs/alpine/world-shared/stf011/atsaris/gnn_results_md_out/mpnn_bzrmd_sDev_new_large

data:
    name: parse_md
    n_train: 28000
    n_valid: 5000
    ### input_dir: '/gpfs/alpine/stf011/world-shared/atsaris/datagnn/datagnn_ras_2020/graph_kRas_monomer_large'
    #filelist: '/gpfs/alpine/world-shared/stf011/atsaris/toy-protmd_new/run00/toy-protmd/graphs/filelist.csv'
    filelist: '/ccs/proj/stf011/atsaris/may2020/gnn-protmd-Toy/gnn-protmd/filelist/filelist.csv'
    batch_size: 64

model:
    name: mpnn3
    n_node_features: 24
    n_edge_features: 3
    hidden_size: 16
    n_outputs: 1
    loss_function: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    lr: 0.001

training:
    n_epochs: 50
